apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dailyclean.fullname" . }}
  labels:
    {{- include "dailyclean.labels" . | nindent 4 }}
rules:
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - pods/exec
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - metrics.k8s.io
    resources:
      - pods
  - verbs:
      - get
      - list
      - watch
      - patch
    apiGroups:
      - apps
      - extensions
    resources:
      - deployments
      - replicasets
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - apps
    resources:
      - statefulsets
  - verbs:
      - get
      - create
      - patch
      - update
      - delete
      - list
      - watch
    apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dailyclean.fullname" . }}
  labels:
    {{- include "dailyclean.labels" . | nindent 4 }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "dailyclean.fullname" . }}
  labels:
    {{- include "dailyclean.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "dailyclean.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "dailyclean.fullname" . }}