---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slimfaas
spec:
  selector:
    matchLabels:
      app: slimfaas
  template:
    metadata:
      labels:
        app: slimfaas
    spec:
      serviceAccountName: slimfaas
      containers:
        - name: slimfaas
          image: axaguildev/slimfaas:latest
          env:
            - name: BASE_FUNCTION_URL
              value: "http://{function_name}.license-preproduction.svc.cluster.local:5000"
            - name: ASPNETCORE_URLS
              value: http://+:5000
            - name: NAMESPACE
              value: "license-preproduction"
            - name: MOCK_REDIS
              value: "true"
            - name : POD_SCALED_UP_BY_DEFAULT_WHEN_INFRASTRUCTURE_HAS_NEVER_CALLED
            - value : "false"
          resources:
            limits:
              memory: "76Mi"
              cpu: "4000m"
            requests:
              memory: "76Mi"
              cpu: "200m"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: slimfaas
spec:
  selector:
    app: slimfaas
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30030