name: DailyClean API Docker Image CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:

  tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        id: bump-version-and-push-tag
        if: github.event_name != 'pull_request'
        uses: hennejg/github-tag-action@v4.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        if: github.event_name != 'pull_request' && steps.bump-version-and-push-tag.outputs.new_tag != undefined'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

  build_api:
    environment: dailyclean
    needs: tags
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: axaguildev/dailyclean-api
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./api
        file: ./api/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=axaguildev/dailyclean-api:buildcache
        cache-to: type=registry,ref=axaguildev/dailyclean-api:buildcache,mode=max

  build_job:
    environment: dailyclean
    needs: tags
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: axaguildev/dailyclean-job
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./job/dailyclean
        file: ./job/dailyclean/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=axaguildev/dailyclean-job:buildcache
        cache-to: type=registry,ref=axaguildev/dailyclean-job:buildcache,mode=max