name: DailyClean API Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#   paths:
#     - 'api'  
#     - '.github' 

jobs:

  build:
    environment: dailyclean

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      working-directory: ./api
      run: docker build . --file Dockerfile --tag docker.io/axaguildev/kubernetes/dailyclean-api:$(date +%s)
#
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      working-directory: ./api
      run: | 
        docker image push docker.io/axaguildev/kubernetes/dailyclean-api:$(date +%s)
  
