name: DailyClean JOB Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
   # paths:
   #   - 'job'  

jobs:

  build:
    environment: dailyclean
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: axaguildev/dailyclean-job
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./job/dailyclean
        file: ./job/dailyclean/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=axaguildev/dailyclean-job:buildcache
        cache-to: type=registry,ref=axaguildev/dailyclean-job:buildcache,mode=max
