name: DailyClean API Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#   paths:
#     - 'api'  
#     - '.github' 

jobs:

  build:
    environment: dailyclean

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./api
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dailyclean-api:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/dailyclean-api:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/dailyclean-api:buildcache,mode=max
