name: DailyClean Docker Images CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  sonar:
    environment: dailyclean
    name: Sonar Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
          
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
        working-directory: ./api/api
        
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: npm install
        run: npm install
        working-directory: ./api/web
        
      - name: npm test
        run: npm test -- --runInBand --coverage --watchAll=false
        working-directory: ./api/web
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=axaguildev
            -Dsonar.projectKey=AxaGuilDEv_dailyclean
            -Dsonar.java.binaries=api/api/target/classes
            -Dsonar.java.libraries=.
            -Dsonar.coverage.jacoco.xmlReportPaths=**/target/jacoco-report/jacoco.xml
            -Dsonar.javascript.lcov.reportPaths=api/web/coverage/lcov.info
            -Dsonar.python.version=3
            -Dsonar.exclusions=**/*.spec.js,**/*.stories.js,**/src/coverage/**,**/*.scss,**/__snapshots__/**,**/node_modules/**,**/src/.storybook/**,**/src/storybook-static/**,**/__mocks__/**
            -Dsonar.coverage.exclusions=**src/test/**/*.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  tags:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.tag.outputs.new_version }}
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        id: tag_version
        if: github.ref == 'refs/heads/main'
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
      - name: Add tag to output step
        id: tag
        if: github.ref == 'refs/heads/main'
        run: echo "::set-output name=new_version::${{ steps.tag_version.outputs.new_version }}"

  build_api:
    environment: dailyclean
    needs: tags
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: axaguildev/dailyclean-api
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
   
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Build and push
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v2
      with:
        context: ./api
        file: ./api/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: axaguildev/dailyclean-api:${{ needs.tags.outputs.new_version }},axaguildev/dailyclean-api:latest
        cache-from: type=registry,ref=axaguildev/dailyclean-api:buildcache
        cache-to: type=registry,ref=axaguildev/dailyclean-api:buildcache,mode=max
    
    - name: Build and push
      if: github.ref != 'refs/heads/main'
      uses: docker/build-push-action@v2
      with:
        context: ./api
        file: ./api/Dockerfile
      #  builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: registry.hub.docker.com/${{ steps.meta.outputs.tags }}
      #  labels: ${{ steps.meta.outputs.labels }}
       # cache-from: type=registry,ref=axaguildev/dailyclean-api:buildcache
       # cache-to: type=registry,ref=axaguildev/dailyclean-api:buildcache,mode=max

  build_job:
    environment: dailyclean
    needs: tags
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: axaguildev/dailyclean-job
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      if: github.ref != 'refs/heads/main'
      with:
        context: ./job/dailyclean
        file: ./job/dailyclean/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: registry.hub.docker.com/${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=axaguildev/dailyclean-job:buildcache
        cache-to: type=registry,ref=axaguildev/dailyclean-job:buildcache,mode=max
    - name: Build and push
      uses: docker/build-push-action@v2
      if: github.ref == 'refs/heads/main'
      with:
        context: ./job/dailyclean
        file: ./job/dailyclean/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: axaguildev/dailyclean-job:${{ needs.tags.outputs.new_version }},axaguildev/dailyclean-job:latest
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=axaguildev/dailyclean-job:buildcache
        cache-to: type=registry,ref=axaguildev/dailyclean-job:buildcache,mode=max
